"""empty message

Revision ID: 4afed87ecf77
Revises: a9b1e0d64231
Create Date: 2024-12-30 12:45:55.077722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afed87ecf77'
down_revision: Union[str, None] = 'a9b1e0d64231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('participant_user_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'participant_user_name')
    # ### end Alembic commands ###
