"""empty message

Revision ID: a9b1e0d64231
Revises: 9da66fa205e7
Create Date: 2024-12-30 12:36:21.683924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b1e0d64231'
down_revision: Union[str, None] = '9da66fa205e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('participant_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'participant_name')
    # ### end Alembic commands ###
